spring.application.name=25AD028

spring.datasource.url=jdbc:mysql://localhost:3306/noteshare
spring.datasource.username=root
spring.datasource.password=darsh123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080